### ISSUE TITLE
Session error: Cannot unsubscribe: An unknown Subscriber

### ISSUE THREAD

**Issue by ashishnagarro** [opentok/opentok-android-sdk-samples#190]
Hi Team,

I am getting error when stream is dropped and i try to unsubscribe that stream.
Earlier it was working fine but now i am getting error always.

Session error: Cannot unsubscribe: An unknown Subscriber instance was passed into Session.unsubscribe().

Could you please look into it and let us know where we are lacking.
Or now is there any changes so no need to unsubscribe when stream is dropped.

Waiting for your inputs.....

**Comment by msach22** [comment]
Hey @ashishnagarro are you only seeing this in 2.15 and above or did this issue exist in 2.14 as well?

**Comment by ashishnagarro** [comment]
I am seeing from 2.15 and above.

**Comment by msach22** [comment]
@ashishnagarro Thanks for confirming. I checked internally and we plan on fixing this with the 2.16 release.

**Comment by igorbiscanin** [comment]
Hey, I am facing the same issue when trying to unsubscribe in `onStreamDropped`.
@msach22 Any info about 2.16 release date?

**Comment by rameshk5085** [comment]
working fine in 2.14

**Comment by robjperez** [comment]
Thanks for reporting!

This should be fixed in 2.16

Closing this issue, please reopen it if you can reproduce while using 2.16.

**Comment by BeenRak** [comment]
Hi @robjperez 
I am facing same issue in version 2.16.2.

**Comment by overpas** [comment]
@robjperez Still facing this issue with "Cannot unsubscribe: An unknown Subscriber instance was passed into Session.unsubscribe()" in opentok version 2.16.3. Please, reopen this issue

**Comment by jaoo** [comment]
Weird. This issue was fixed in Android 2.16.2. It won't be in the upcoming Android 2.17.0 release either.

**Comment by jaoo** [comment]
I am closing this issue. Please reopen if someone reproduces it with Android 2.17.0. Thanks.
