### ISSUE TITLE
Textureview does not scale properly when resizing in pip mode

### ISSUE THREAD

**Issue by jitheeshex** [opentok/opentok-android-sdk-samples#195]
When using mSession with texture view options true, and the conatiner view is resized, content in textureview is not scaled. While in GLSurfaceView the problem does not occur.
```
mSession = new Session.Builder(requireContext(), OpenTokConfig.API_KEY, OpenTokConfig.SESSION_ID)
                        .sessionOptions(new Session.SessionOptions() {
                            @Override
                            public boolean useTextureViews() {
                                return true;
                            }
                        })
                        .build();
```

**Comment by jitheeshex** [comment]
I see such an issue was reported as fixed in 2.14.1

> When resizing a TextureView containing an OpenTok video, the resized view does not scale the whole video correctly and results in a cropped video. However, when resizing a GLSurfaceView containing an OpenTok video, the resized view produces a properly scaled video. This issue was introduced in v2.14.0.

**Comment by projectAZB** [comment]
I'm using 2.15.3 and this is still an issue for me. Please update us with an ETA on the fix

**Comment by jintgeorge** [comment]
This has been fixed with 2.16.1 release.
